---
driver_plugin: digitalocean
provisioner: chef_zero
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-13.10
- name: debian-7.0
suites:
- name: default
  run_list:
  - recipe[tarsnap]
  - recipe[tarsnap_test]
  attributes:
    tarsnap_keys:

