---
driver_plugin: digitalocean
provisioner: chef_zero
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-13.10
  run_list:
  - recipe[ubuntu]
- name: debian-7.0
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
  - recipe[tarsnap]
  - recipe[minitest-handler]
  attributes:
    tarsnap_keys:

